// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scaffold_migration.Models;

#nullable disable

namespace scaffoldmigration.Migrations
{
    [DbContext(typeof(NhanvienContext))]
    [Migration("20221201094628_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scaffold_migration.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEPT_NAME");

                    b.Property<string>("DeptNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DEPT_NO");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LOCATION");

                    b.HasKey("DeptId")
                        .HasName("PK__DEPARTME__512A59AC999F51A7");

                    b.HasIndex(new[] { "DeptNo" }, "UQ__DEPARTME__512A302D197A5DD5")
                        .IsUnique();

                    b.ToTable("DEPARTMENT", (string)null);
                });

            modelBuilder.Entity("scaffold_migration.Models.Employee", b =>
                {
                    b.Property<decimal>("EmpId")
                        .HasColumnType("numeric(19, 0)")
                        .HasColumnName("EMP_ID");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DEPT_ID");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("EMP_NAME");

                    b.Property<string>("EmpNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("EMP_NO");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("HIRE_DATE");

                    b.Property<byte[]>("Image")
                        .HasColumnType("image")
                        .HasColumnName("IMAGE");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("JOB");

                    b.Property<decimal?>("MngId")
                        .HasColumnType("numeric(19, 0)")
                        .HasColumnName("MNG_ID");

                    b.Property<double>("Salary")
                        .HasColumnType("float")
                        .HasColumnName("SALARY");

                    b.HasKey("EmpId")
                        .HasName("PK__EMPLOYEE__16EBFA26083DB420");

                    b.HasIndex("DeptId");

                    b.HasIndex("MngId");

                    b.HasIndex(new[] { "EmpNo" }, "UQ__EMPLOYEE__16EB127C4EA884EA")
                        .IsUnique();

                    b.ToTable("EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("scaffold_migration.Models.SalaryGrade", b =>
                {
                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasColumnName("GRADE");

                    b.Property<double>("HighSalary")
                        .HasColumnType("float")
                        .HasColumnName("HIGH_SALARY");

                    b.Property<double>("LowSalary")
                        .HasColumnType("float")
                        .HasColumnName("LOW_SALARY");

                    b.HasKey("Grade")
                        .HasName("PK__SALARY_G__B80884C7ED963CFA");

                    b.ToTable("SALARY_GRADE", (string)null);
                });

            modelBuilder.Entity("scaffold_migration.Models.Timekeeper", b =>
                {
                    b.Property<string>("TimekeeperId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("Timekeeper_Id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Date_Time");

                    b.Property<decimal>("EmpId")
                        .HasColumnType("numeric(19, 0)")
                        .HasColumnName("EMP_ID");

                    b.Property<string>("InOut")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("In_Out")
                        .IsFixedLength();

                    b.HasKey("TimekeeperId")
                        .HasName("PK__TIMEKEEP__3421CD0F46BA6804");

                    b.HasIndex("EmpId");

                    b.ToTable("TIMEKEEPER", (string)null);
                });

            modelBuilder.Entity("scaffold_migration.Models.Employee", b =>
                {
                    b.HasOne("scaffold_migration.Models.Department", "Dept")
                        .WithMany("Employees")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK75C8D6AE269A3C9");

                    b.HasOne("scaffold_migration.Models.Employee", "Mng")
                        .WithMany("InverseMng")
                        .HasForeignKey("MngId")
                        .HasConstraintName("FK75C8D6AE13C12F64");

                    b.Navigation("Dept");

                    b.Navigation("Mng");
                });

            modelBuilder.Entity("scaffold_migration.Models.Timekeeper", b =>
                {
                    b.HasOne("scaffold_migration.Models.Employee", "Emp")
                        .WithMany("Timekeepers")
                        .HasForeignKey("EmpId")
                        .IsRequired()
                        .HasConstraintName("FK744D9BFF6106A42");

                    b.Navigation("Emp");
                });

            modelBuilder.Entity("scaffold_migration.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("scaffold_migration.Models.Employee", b =>
                {
                    b.Navigation("InverseMng");

                    b.Navigation("Timekeepers");
                });
#pragma warning restore 612, 618
        }
    }
}
