IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [DEPARTMENT] (
    [DEPT_ID] int NOT NULL,
    [DEPT_NAME] varchar(255) NOT NULL,
    [DEPT_NO] varchar(20) NOT NULL,
    [LOCATION] varchar(255) NULL,
    CONSTRAINT [PK__DEPARTME__512A59AC999F51A7] PRIMARY KEY ([DEPT_ID])
);
GO

CREATE TABLE [SALARY_GRADE] (
    [GRADE] int NOT NULL,
    [HIGH_SALARY] float NOT NULL,
    [LOW_SALARY] float NOT NULL,
    CONSTRAINT [PK__SALARY_G__B80884C7ED963CFA] PRIMARY KEY ([GRADE])
);
GO

CREATE TABLE [EMPLOYEE] (
    [EMP_ID] numeric(19,0) NOT NULL,
    [EMP_NAME] varchar(250) NOT NULL,
    [EMP_NO] varchar(200) NOT NULL,
    [HIRE_DATE] datetime NOT NULL,
    [IMAGE] image NULL,
    [JOB] varchar(30) NOT NULL,
    [SALARY] float NOT NULL,
    [DEPT_ID] int NOT NULL,
    [MNG_ID] numeric(19,0) NULL,
    CONSTRAINT [PK__EMPLOYEE__16EBFA26083DB420] PRIMARY KEY ([EMP_ID]),
    CONSTRAINT [FK75C8D6AE13C12F64] FOREIGN KEY ([MNG_ID]) REFERENCES [EMPLOYEE] ([EMP_ID]),
    CONSTRAINT [FK75C8D6AE269A3C9] FOREIGN KEY ([DEPT_ID]) REFERENCES [DEPARTMENT] ([DEPT_ID])
);
GO

CREATE TABLE [TIMEKEEPER] (
    [Timekeeper_Id] varchar(36) NOT NULL,
    [Date_Time] datetime NOT NULL,
    [In_Out] char(1) NOT NULL,
    [EMP_ID] numeric(19,0) NOT NULL,
    CONSTRAINT [PK__TIMEKEEP__3421CD0F46BA6804] PRIMARY KEY ([Timekeeper_Id]),
    CONSTRAINT [FK744D9BFF6106A42] FOREIGN KEY ([EMP_ID]) REFERENCES [EMPLOYEE] ([EMP_ID])
);
GO

CREATE UNIQUE INDEX [UQ__DEPARTME__512A302D197A5DD5] ON [DEPARTMENT] ([DEPT_NO]);
GO

CREATE INDEX [IX_EMPLOYEE_DEPT_ID] ON [EMPLOYEE] ([DEPT_ID]);
GO

CREATE INDEX [IX_EMPLOYEE_MNG_ID] ON [EMPLOYEE] ([MNG_ID]);
GO

CREATE UNIQUE INDEX [UQ__EMPLOYEE__16EB127C4EA884EA] ON [EMPLOYEE] ([EMP_NO]);
GO

CREATE INDEX [IX_TIMEKEEPER_EMP_ID] ON [TIMEKEEPER] ([EMP_ID]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20221201092745_V1', N'7.0.0');
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20221201094628_V2', N'7.0.0');
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

ALTER TABLE [EMPLOYEE] ADD [Info_EMP] nvarchar(500) NOT NULL DEFAULT N'';
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20221201095253_V3', N'7.0.0');
GO

COMMIT;
GO

